// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeZoviReg.Persistence.Ef;

#nullable disable

namespace NeZoviReg.Migrations.Ef.Migrations
{
    [DbContext(typeof(NeZoviRegDataContext))]
    [Migration("20230811150510_User_Phonenumber_UniqueIndex_Removed")]
    partial class User_Phonenumber_UniqueIndex_Removed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 941, DateTimeKind.Local).AddTicks(6018),
                            Name = "RegUsersOnly",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 941, DateTimeKind.Local).AddTicks(6060),
                            Name = "Read",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 941, DateTimeKind.Local).AddTicks(6062),
                            Name = "Delete",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 941, DateTimeKind.Local).AddTicks(6064),
                            Name = "Write",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("RegUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RegUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RegUserId = 1,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 948, DateTimeKind.Local).AddTicks(8154),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RegUserId = 2,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 948, DateTimeKind.Local).AddTicks(8220),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(4556),
                            Name = "Admin",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(4578),
                            Name = "Obveznik",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(4580),
                            Name = "Trgovac",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(9501),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(9516),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(9518),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(9519),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 952, DateTimeKind.Local).AddTicks(9521),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ForgotPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ForgotPasswordTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RegNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RegUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Palmotićeva 2",
                            CompanyName = "RATEL",
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 953, DateTimeKind.Local).AddTicks(3789),
                            Email = "mail@mail.com",
                            FirstName = "Ime",
                            GuidId = new Guid("094ef666-7793-4694-a4b9-d53015c1fbca"),
                            LastName = "Prezime",
                            Password = "dGVzdDEyMw==",
                            RegNumber = "00000000",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxNumber = "000000000",
                            Username = "ratel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Palmotićeva 2",
                            CompanyName = "RATEL2",
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 8, 11, 17, 5, 9, 953, DateTimeKind.Local).AddTicks(3816),
                            Email = "mail2@mail.com",
                            FirstName = "Ime",
                            GuidId = new Guid("13f54b2d-f186-46ee-9af4-c45d2e9f76e6"),
                            LastName = "Prezime",
                            Password = "dGVzdDEyMw==",
                            RegNumber = "11111111",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxNumber = "111111111",
                            Username = "ratel2"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "RegUser")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RegUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", "Role")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("RegUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Auth.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Navigation("RegUserRoles");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Navigation("RegUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
