// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeZoviReg.Persistence.Ef;

#nullable disable

namespace NeZoviReg.Migrations.Ef.Migrations
{
    [DbContext(typeof(NeZoviRegDataContext))]
    [Migration("20230523092613_RegUser_Add_RefreshToken")]
    partial class RegUser_Add_RefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 720, DateTimeKind.Local).AddTicks(483),
                            Name = "All"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 720, DateTimeKind.Local).AddTicks(534),
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 720, DateTimeKind.Local).AddTicks(536),
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 720, DateTimeKind.Local).AddTicks(538),
                            Name = "ReadAll"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 720, DateTimeKind.Local).AddTicks(540),
                            Name = "Write"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("RegUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RegUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RegUserId = 1,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 731, DateTimeKind.Local).AddTicks(2910)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 736, DateTimeKind.Local).AddTicks(4877),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 736, DateTimeKind.Local).AddTicks(4916),
                            Name = "Obveznik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 736, DateTimeKind.Local).AddTicks(4919),
                            Name = "Trgovac"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 736, DateTimeKind.Local).AddTicks(4921),
                            Name = "Potrosac"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(1997)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(2012)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(2014)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(2015)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(2017)
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(2035)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("RegNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RegUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Palmotićeva 2",
                            CompanyName = "RATEL",
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2023, 5, 23, 11, 26, 13, 737, DateTimeKind.Local).AddTicks(8034),
                            FirstName = "Ime",
                            GuidId = new Guid("3ccf33ed-8a07-4d3d-b0af-62bdb9b2e4ee"),
                            LastName = "Prezime",
                            Password = "dGVzdDEyMw==",
                            RegNumber = "17606590",
                            TaxNumber = "103986571",
                            Username = "ratel"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OperatorId")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "RegUser")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RegUserId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", "Role")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("RegUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Auth.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Navigation("RegUserRoles");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Navigation("RegUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
