// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeZoviReg.Persistence.Ef;

#nullable disable

namespace NeZoviReg.Migrations.Ef.Migrations
{
    [DbContext(typeof(NeZoviRegDataContext))]
    [Migration("20240331120804_AddUserAccount")]
    partial class AddUserAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 948, DateTimeKind.Local).AddTicks(129),
                            Name = "RegUsersOnly",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 948, DateTimeKind.Local).AddTicks(174),
                            Name = "Read",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 948, DateTimeKind.Local).AddTicks(176),
                            Name = "Delete",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 948, DateTimeKind.Local).AddTicks(178),
                            Name = "Write",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("RegUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RegUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RegUserId = 1,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 964, DateTimeKind.Local).AddTicks(1177),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RegUserId = 2,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 964, DateTimeKind.Local).AddTicks(1235),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 968, DateTimeKind.Local).AddTicks(6123),
                            Name = "Admin",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 968, DateTimeKind.Local).AddTicks(6161),
                            Name = "Obveznik",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 968, DateTimeKind.Local).AddTicks(6164),
                            Name = "Trgovac",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(3469),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(3484),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(3486),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(3488),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 16,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(3490),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccessTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("varchar(88)");

                    b.Property<string>("ForgotPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ForgotPasswordTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RegUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(8126),
                            Email = "mail@mail.com",
                            GuidId = new Guid("17180e40-4fee-44ed-bbbb-5402b21a0750"),
                            Password = "dGVzdDEyMw==",
                            RegUserId = 1,
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "ratel"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 969, DateTimeKind.Local).AddTicks(8157),
                            Email = "mail@mail.com",
                            GuidId = new Guid("4284255e-e5aa-4f6e-9b7c-98f00c47c8b1"),
                            Password = "dGVzdDEyMw==",
                            RegUserId = 2,
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "ratel2"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.UserAccountRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccountRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 970, DateTimeKind.Local).AddTicks(7343),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1,
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 970, DateTimeKind.Local).AddTicks(7371),
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AccessTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ForgotPasswordToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ForgotPasswordTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GuidId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RegNumber")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RegUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Palmotićeva 2",
                            CompanyName = "RATEL",
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 971, DateTimeKind.Local).AddTicks(4026),
                            Email = "mail@mail.com",
                            FirstName = "Ime",
                            GuidId = new Guid("41816c3f-4f4d-41c8-ae4e-bae6b4d17194"),
                            LastName = "Prezime",
                            Password = "dGVzdDEyMw==",
                            RegNumber = "00000000",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxNumber = "000000000",
                            Username = "ratel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Palmotićeva 2",
                            CompanyName = "RATEL2",
                            CreatedBy = "init",
                            CreatedOn = new DateTime(2024, 3, 31, 14, 8, 3, 971, DateTimeKind.Local).AddTicks(4073),
                            Email = "mail2@mail.com",
                            FirstName = "Ime",
                            GuidId = new Guid("0291fdaa-3a29-4c75-99c1-288d45337952"),
                            LastName = "Prezime",
                            Password = "dGVzdDEyMw==",
                            RegNumber = "11111111",
                            Rowversion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxNumber = "111111111",
                            Username = "ratel2"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("Rowversion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "RegUser")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RegUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", "Role")
                        .WithMany("RegUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("RegUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Auth.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.UserAccount", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", null)
                        .WithMany("UserAccounts")
                        .HasForeignKey("RegUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.UserAccountRole", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", "Role")
                        .WithMany("UserAccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.UserAccount", "UserAccount")
                        .WithMany("UserAccountRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Navigation("RegUserRoles");

                    b.Navigation("UserAccountRoles");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.UserAccount", b =>
                {
                    b.Navigation("UserAccountRoles");
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Navigation("RegUserRoles");

                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
