// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeZoviReg.Persistence.Ef;

#nullable disable

namespace NeZoviReg.Migrations.Ef.Migrations
{
    [DbContext(typeof(NeZoviRegDataContext))]
    [Migration("20230419075025_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 114, DateTimeKind.Local).AddTicks(4584),
                            Name = "All"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 114, DateTimeKind.Local).AddTicks(4589),
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 114, DateTimeKind.Local).AddTicks(4592),
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 114, DateTimeKind.Local).AddTicks(4595),
                            Name = "ReadAll"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 114, DateTimeKind.Local).AddTicks(4597),
                            Name = "Write"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.Property<int>("RegUserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("RegUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RegUserRole", (string)null);

                    b.HasData(
                        new
                        {
                            RegUserId = 1,
                            RoleId = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 115, DateTimeKind.Local).AddTicks(6222)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(3459),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(3465),
                            Name = "Obveznik"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(3469),
                            Name = "Trgovac"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(3472),
                            Name = "Potrosac"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9080)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9084)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9086)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9089)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9092)
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 124, DateTimeKind.Local).AddTicks(9094)
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.Property<string>("ThumbPrint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("RegUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 125, DateTimeKind.Local).AddTicks(3152),
                            Email = "petar.petrovic@mts.rs",
                            FirstName = "Petar",
                            LastName = "Petrovic",
                            Password = "dGVzdDEyMw==",
                            Username = "pPetrovic"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Jmbg")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<byte[]>("Rowversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(8)
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "test",
                            CreatedOn = new DateTime(2023, 4, 19, 9, 50, 25, 128, DateTimeKind.Local).AddTicks(1242),
                            FirstName = "Marko",
                            Jmbg = "012345567",
                            LastName = "Bubulj",
                            PhoneNumber = "1234"
                        });
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RegUserRole", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Domain.RegUser", null)
                        .WithMany()
                        .HasForeignKey("RegUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NeZoviReg.Domain.Model.Auth.RolePermission", b =>
                {
                    b.HasOne("NeZoviReg.Domain.Model.Auth.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeZoviReg.Domain.Model.Auth.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
